#!/usr/bin/env bash
# validate-skills.sh — Validate SKILL.md frontmatter and kit doc links for a pack
#
# Usage:
#   bash scripts/validate-skills.sh --pack=core
#   ./scripts/kit validate-skills --pack=core [--report=path.md]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KIT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
PACK=""
REPORT=""
ERRORS=0
WARNINGS=0

for arg in "$@"; do
  case "$arg" in
    --pack=*) PACK="${arg#--pack=}" ;;
    --report=*) REPORT="${arg#--report=}" ;;
    --help|-h)
      echo "Usage: $0 --pack=core [--report=packs/core/validate-report.md]"
      exit 0
      ;;
  esac
done

[[ -n "$PACK" ]] || { echo "ERROR: --pack= required" >&2; exit 1; }

[[ -n "$REPORT" && "$REPORT" != /* ]] && REPORT="$KIT_DIR/$REPORT"

MANIFEST="$KIT_DIR/packs/$PACK/manifest.json"
[[ -f "$MANIFEST" ]] || { echo "ERROR: missing $MANIFEST" >&2; exit 1; }

err() { echo "ERROR: $*" >&2; ERRORS=$((ERRORS + 1)); }
warn() { echo "WARN: $*" >&2; WARNINGS=$((WARNINGS + 1)); }
ok() { echo "  ok: $*"; }

trim_ws() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

report_line() {
  [[ -n "$REPORT" ]] || return 0
  echo "$1" >> "$REPORT"
}

init_report() {
  [[ -z "$REPORT" ]] && return
  mkdir -p "$(dirname "$REPORT")"
  cat > "$REPORT" <<EOF
# Skills validation report: pack $PACK

Generated by \`validate-skills.sh\`. Agent reviews content against official docs; human signs off in the PR (see docs/skills-review.md).

| Skill | Frontmatter | profile.yaml | Doc links | Agent | Human |
|-------|-------------|--------------|-----------|-------|-------|
EOF
}

check_doc_links() {
  local skill_dir="$1" skill="$2"
  local skill_md="$skill_dir/SKILL.md"
  local link_err=0
  while IFS= read -r rel; do
    [[ -z "$rel" ]] && continue
    local target="$skill_dir/$rel"
    target="${target//\/\.\//\/}"
    if [[ ! -f "$target" ]]; then
      warn "$skill: broken link in SKILL.md → $rel"
      link_err=1
    fi
  done < <(grep -oE '\(\.\./[^)]+\)' "$skill_md" 2>/dev/null | tr -d '()' || true)
  [[ $link_err -eq 0 ]]
}

parse_frontmatter() {
  local skill_md="$1"
  ruby -ryaml -e "
    text = File.read('$skill_md')
    m = text.match(/\A---\s*\n(.*?)\n---/m)
    unless m
      puts 'MISSING'
      exit 0
    end
    data = YAML.safe_load(m[1]) rescue nil
    unless data.is_a?(Hash)
      puts 'INVALID'
      exit 0
    end
    puts data['name'].to_s
    puts '---SPLIT---'
    puts data['description'].to_s
  " 2>/dev/null || echo "MISSING"
}

init_report

echo "Validating skills for pack '$PACK' at $KIT_DIR"
echo ""

while IFS= read -r skill; do
  [[ -z "$skill" ]] && continue
  skill_dir="$KIT_DIR/skills/$skill"
  skill_md="$skill_dir/SKILL.md"

  fm_ok="PASS"
  profile_ok="SKIP"
  links_ok="PASS"
  agent_col="pending"
  human_col="pending"

  if [[ ! -f "$skill_md" ]]; then
    err "missing skills/$skill/SKILL.md"
    fm_ok="FAIL"
    links_ok="FAIL"
    report_line "| $skill | FAIL | — | FAIL | pending | pending |"
    continue
  fi

  parsed=$(parse_frontmatter "$skill_md")
  if [[ "$parsed" == "MISSING" || "$parsed" == "INVALID" ]]; then
    err "$skill: invalid or missing YAML frontmatter"
    fm_ok="FAIL"
  else
    name="${parsed%%---SPLIT---*}"
    desc="${parsed#*---SPLIT---}"
    name="$(trim_ws "$name")"
    desc="$(trim_ws "$desc")"
    if [[ -z "$name" ]]; then
      err "$skill: frontmatter missing name"
      fm_ok="FAIL"
    fi
    if [[ -z "$desc" ]]; then
      err "$skill: frontmatter missing description"
      fm_ok="FAIL"
    fi
    if [[ ${#desc} -lt 20 ]]; then
      warn "$skill: description very short (${#desc} chars) — may not trigger implicit invocation"
    fi
  fi

  if [[ "$skill" == stacks/* ]]; then
    if [[ -f "$skill_dir/profile.yaml" ]]; then
      profile_ok="PASS"
    else
      err "$skill: missing profile.yaml"
      profile_ok="FAIL"
    fi
  fi

  if ! check_doc_links "$skill_dir" "$skill"; then
    links_ok="FAIL"
  fi

  if [[ "$fm_ok" == "PASS" && "$links_ok" == "PASS" && "$profile_ok" != "FAIL" ]]; then
    ok "$skill"
  fi

  report_line "| $skill | $fm_ok | $profile_ok | $links_ok | $agent_col | $human_col |"

done < <(jq -r '.skills[]' "$MANIFEST")

echo ""
if [[ -n "$REPORT" ]]; then
  echo "Report written: $REPORT"
fi

if [[ $ERRORS -gt 0 ]]; then
  echo "FAILED: $ERRORS error(s), $WARNINGS warning(s)"
  exit 1
fi
echo "PASSED skills validation ($WARNINGS warning(s))"
